# Generated by Django 4.2.7 on 2024-12-13 12:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('timeframe', models.CharField(default='1h', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.tradingpair')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('direction', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down')], max_length=4)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes')], max_length=2)),
                ('current_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('target_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('technical_indicators', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.tradingpair')),
            ],
            options={
                'ordering': ['-prediction_time'],
            },
        ),
        migrations.CreateModel(
            name='AccuracyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes')], max_length=2)),
                ('total_predictions', models.IntegerField(default=0)),
                ('correct_predictions', models.IntegerField(default=0)),
                ('accuracy_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.tradingpair')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pricedata',
            unique_together={('trading_pair', 'timestamp', 'timeframe')},
        ),
        migrations.AlterUniqueTogether(
            name='accuracymetrics',
            unique_together={('trading_pair', 'timeframe')},
        ),
    ]