# Generated by Django 4.2 on 2025-12-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accuracymetrics',
            name='timeframe',
            field=models.CharField(choices=[('5m', '5 Minutes'), ('1m', '1 Minute')], max_length=2),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='timeframe',
            field=models.CharField(choices=[('5m', '5 Minutes'), ('1m', '1 Minute')], max_length=2),
        ),
    ]
