# Generated by Django 5.2.9 on 2025-12-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_alter_accuracymetrics_timeframe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_image', models.ImageField(help_text='Upload 1-hour chart image', upload_to='charts/')),
                ('symbol', models.CharField(help_text='Trading pair symbol (e.g., EURUSD)', max_length=20)),
                ('timeframe', models.CharField(choices=[('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day')], default='1h', max_length=3)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_completed', models.BooleanField(default=False)),
                ('analysis_result', models.JSONField(blank=True, default=dict)),
                ('market_structure', models.JSONField(blank=True, default=dict)),
                ('support_resistance', models.JSONField(blank=True, default=dict)),
                ('trend_analysis', models.JSONField(blank=True, default=dict)),
                ('pattern_recognition', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
