# Generated by Django 5.2.9 on 2025-12-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_chartupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChartUpload',
        ),
    ]
