# Generated by Django 5.2.9 on 2025-12-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_delete_chartupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_image', models.ImageField(help_text='Upload 15-minute or 1-hour chart image', upload_to='charts/')),
                ('symbol', models.CharField(help_text='Trading pair symbol (e.g., EURUSD)', max_length=20)),
                ('timeframe', models.CharField(choices=[('15m', '15 Minutes'), ('1h', '1 Hour')], default='1h', max_length=3)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_completed', models.BooleanField(default=False)),
                ('chart_analysis', models.JSONField(blank=True, default=dict, help_text='Visual chart pattern analysis')),
                ('market_structure', models.JSONField(blank=True, default=dict, help_text='Market structure from chart')),
                ('real_price_prediction', models.JSONField(blank=True, default=dict, help_text='Prediction using real price data')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
